In [1]:
import tensorflow as tf

In [2]:
import numpy as np

In [3]:
m_a = tf.constant([[1., 2.], [3., 4.]], dtype=tf.float32)
m_b = tf.constant([[5., 6.], [7., 8.]], dtype=tf.float32)

In [4]:
print(f"Matrix A:\n{m_a.numpy()}")
print(f"Matrix B:\n{m_b.numpy()}")


Matrix A:
[[1. 2.]
 [3. 4.]]
Matrix B:
[[5. 6.]
 [7. 8.]]


In [6]:
product = tf.linalg.matmul(m_a, m_b)

In [7]:
print(f"\nProduct of A * B:\n{product.numpy()}")


Product of A * B:
[[19. 22.]
 [43. 50.]]


In [9]:
symmetric_matrix = tf.constant([[4., 1.], [1., 3.]], dtype=tf.float32)

In [10]:
eigenvalues, eigenvectors = tf.linalg.eigh(symmetric_matrix)

In [11]:
print(f"\nEigenvalues:\n{eigenvalues.numpy()}")


Eigenvalues:
[2.3819664 4.6180344]


In [12]:
print(f"\nEigenvectors (columns):\n{eigenvectors.numpy()}")


Eigenvectors (columns):
[[-0.52573115  0.85065085]
 [ 0.85065085  0.52573115]]
